/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;
import Backend.EmployeeRole;
/**
 *
 * @author 20127
 */
public class EmployeeRoleWindow extends javax.swing.JFrame implements Node{

    /**
     * Creates new form EmployeeRole
     */
    private Node parent;
    private EmployeeRole employeerole;
    private AddProductWindow addproduct;
    private PurchaseProductWindow purchaseproduct;
    private ViewProductsWindow viewproducts;
    private ViewPurchasedProductsWindow viewpurchasedproducts;
    private ReturnProductWindow returnproduct;
    
    public EmployeeRoleWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        employeerole = new EmployeeRole();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addProduct_btn = new javax.swing.JButton();
        purchaseProduct_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        viewProducts_btn = new javax.swing.JButton();
        viewPurchasedProducts_btn = new javax.swing.JButton();
        returnProduct_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Employee Role");

        addProduct_btn.setBackground(new java.awt.Color(0, 0, 0));
        addProduct_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addProduct_btn.setForeground(new java.awt.Color(255, 255, 255));
        addProduct_btn.setText("Add Product");
        addProduct_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        addProduct_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProduct_btnActionPerformed(evt);
            }
        });

        purchaseProduct_btn.setBackground(new java.awt.Color(0, 0, 0));
        purchaseProduct_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        purchaseProduct_btn.setForeground(new java.awt.Color(255, 255, 255));
        purchaseProduct_btn.setText("Purchase Product");
        purchaseProduct_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        purchaseProduct_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseProduct_btnActionPerformed(evt);
            }
        });

        logout_btn.setBackground(new java.awt.Color(0, 0, 0));
        logout_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setText("Logout");
        logout_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        viewProducts_btn.setBackground(new java.awt.Color(0, 0, 0));
        viewProducts_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewProducts_btn.setForeground(new java.awt.Color(255, 255, 255));
        viewProducts_btn.setText("View Products");
        viewProducts_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        viewProducts_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProducts_btnActionPerformed(evt);
            }
        });

        viewPurchasedProducts_btn.setBackground(new java.awt.Color(0, 0, 0));
        viewPurchasedProducts_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewPurchasedProducts_btn.setForeground(new java.awt.Color(255, 255, 255));
        viewPurchasedProducts_btn.setText("View Purchased Products");
        viewPurchasedProducts_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        viewPurchasedProducts_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPurchasedProducts_btnActionPerformed(evt);
            }
        });

        returnProduct_btn.setBackground(new java.awt.Color(0, 0, 0));
        returnProduct_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnProduct_btn.setForeground(new java.awt.Color(255, 255, 255));
        returnProduct_btn.setText("Return Product");
        returnProduct_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        returnProduct_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnProduct_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProduct_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewProducts_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchaseProduct_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewPurchasedProducts_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(returnProduct_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(addProduct_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewProducts_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(purchaseProduct_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewPurchasedProducts_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returnProduct_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProduct_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProduct_btnActionPerformed
        if(addproduct == null)
            addproduct=new AddProductWindow(employeerole);
        addproduct.setParent(this);
        addproduct.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addProduct_btnActionPerformed

    private void purchaseProduct_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseProduct_btnActionPerformed
        if(purchaseproduct == null)
            purchaseproduct=new PurchaseProductWindow(employeerole);
        purchaseproduct.setParent(this);
        purchaseproduct.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_purchaseProduct_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        employeerole.logout();
        ((InventorySystemWindow)parent).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logout_btnActionPerformed

    private void viewProducts_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProducts_btnActionPerformed
        if(viewproducts == null)
            viewproducts=new ViewProductsWindow(employeerole);
        viewproducts.setParent(this);
        viewproducts.setData();
        viewproducts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewProducts_btnActionPerformed

    private void viewPurchasedProducts_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPurchasedProducts_btnActionPerformed
        if(viewpurchasedproducts == null)
            viewpurchasedproducts=new ViewPurchasedProductsWindow(employeerole);
        viewpurchasedproducts.setParent(this);
        viewpurchasedproducts.setData();
        viewpurchasedproducts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewPurchasedProducts_btnActionPerformed

    private void returnProduct_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnProduct_btnActionPerformed
        if(returnproduct == null)
            returnproduct=new ReturnProductWindow(employeerole);
        returnproduct.setParent(this);
        returnproduct.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnProduct_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRoleWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton purchaseProduct_btn;
    private javax.swing.JButton returnProduct_btn;
    private javax.swing.JButton viewProducts_btn;
    private javax.swing.JButton viewPurchasedProducts_btn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setParent(Node parent) {
        this.parent = parent;
    }

    @Override
    public Node getParents() {
        return parent;
    }
}
